[package]
name = "brshtop"
version = "0.0.1"
authors = ["Aristocratos <jakob@qvantnet.com>","Samuel Rembisz <sjrembisz07@gmail.com>", "Charlie Thomson <charliecthomson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
psutil = "3.2.0"
string_template = "0.2.1"
expanduser = "1.2.1"
log = "0.4.11"
simple-logging = "2.0.2"
lenient_bool = "0.1.1"
terminal_size = "0.1.15"
lazy_static = "1.4.0"
regex = "1.4.2"
from_map = { version = '0.1.0', path = "./from_map" }
gradient = { version = '0.1.0', path = "./gradient" }