[package]
name = "brshtop"
version = "0.0.1"
authors = ["Samuel Rembisz <sjrembisz07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
psutil = "3.2.0"
string_template = "0.2.1"
expanduser = "1.2.1"